### ISSUE TITLE
Fix indentation

### ISSUE THREAD

**Issue by shadyvb** [msharafjr/FCBarcelona#1]
اول حاجة اى حد بيبص عليها خصوصا لما تكون كاتب الكود من الاول هى شكل الكود عامل ازاى

 واول حاجة فى شكل هو استعمالك للمسافات
يعنى مينفعش سطرين جوا نفس التاج يبدئوا من نقطتين مختلفين

``` html
<head>
  <title>Bla bla</title>
       <link src="blablah.com/style.css" />
</head>
```

ده غلط

``` html
<head>
  <title>Bla bla</title>
  <link src="blablah.com/style.css" />
</head>
```

ده صح

وعموما .. خلى البرنامج اللى انتا شغال بيه يشتغل بالتاب ( Tab ) مش بالمسافة العادية ، يعنى المسافة اللى قبل السطر تبقى Tab واحدة او اكتر ، مش مسافتين او اربعة او اكتر

دور فى البرنامج اللى بتستخدمه على اوبشن الIndentation، هتلاقيه بيديلك اختيارين مابين التاب او مسافتين او اربعة او اكتر

ليه بنستعمل التاب: عشان تقدر عن طريق البرنامج اللى بتشتغل بيه تقوله خلى مسافة التاب كبيرة او صغيرة حسب ما بتحب تشوف وتشتغل على الكود ، من غير ماتغير كمية المسافات عشان تظبط المساحات مابين الكلام زى ماتحب

Read: http://mrbool.com/importance-of-code-indentation/29079

وفى لغة زى الPython مثلا بتفرق مابين الاكواد عن طريق التاب ، مش زي الـJS عن طريق الاقواس

``` python
if test == 1:
    do something
```

^^ Correct

``` python
if test == 1:
do something
```

^^ ERROR

ملحوظة: لو الكلام العربى وانجليزي فى نفس السطر مش باين كويس ( وهو فعلا ملخبط ) خده كوبى وبيست فى اي برنامج تانى ، وهات الكلام من اليمين للشمال عشان تعرف تقراه. لحد مانشوف حل للقصة دى.

**Comment by msharafjr** [comment]
My bad
بس انا بشوف كود معظم المواقع مثلا فى تاج معين جواه تاجات متفرعة 
like this 

```

<div id="asd">
  <div id="sdf">
     <ul id="asd_sdf">
       <li>some text</li>
       <li>some text</li>
       <li>some text</li>
     </ul>
  </div>
</div>

```

بناءاً عليه انا كتبت الكود كده

**Comment by shadyvb** [comment]
ايوه المثال ده صح ، انا بتكلم على كمية المسافات واستعمال التاب بدل المسافة

بص على اللينك ده :
https://github.com/msharaf10/FCBarcelona/blob/e4e4d901847710559050e89fd1a3eabbec508280/FCB%201.html

لسه فى حاجات مش متظبطة
